build:
  environment:
    php: 7.1.0

  dependencies:
    before:
      # Download and verify latest Composer installer. See more https://getcomposer.org/download
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php -r "if (hash_file('sha384', 'composer-setup.php') === 'ed0feb545ba87161262f2d45a633e34f591ebb3381f2e0063c345ebea4d228dd0043083717770234ec00c5a9f9593792') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
      - php composer-setup.php --install-dir=$HOME/bin --filename=composer
      - php -r "unlink('composer-setup.php');"
      - $HOME/bin/composer --version
    override:
      - $HOME/bin/composer install --no-interaction --prefer-dist --optimize-autoloader --no-plugins

  nodes:
    analysis:
      tests:
        override:
          - "php-scrutinizer-run"

checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - vendor/*